apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_VERSION
              value: {{ .Values.config.appVersion | quote }}
            {{- if .Values.config.giphyApiKey }}
            - name: GIPHY_API_KEY
              value: {{ .Values.config.giphyApiKey | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
